/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as UsersRouteImport } from './routes/users'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AutomationsIndexRouteImport } from './routes/automations/index'
import { Route as AutomationsAutomationIdRouteRouteImport } from './routes/automations/$automationId/route'
import { Route as AutomationsAutomationIdIndexRouteImport } from './routes/automations/$automationId/index'
import { Route as AutomationsAutomationIdActivityRouteImport } from './routes/automations/$automationId/activity'
import { Route as AutomationsAutomationIdContentRouteImport } from './routes/automations/$automationId/content'
import { Route as AutomationsAutomationIdDirectMessageRouteImport } from './routes/automations/$automationId/direct-message'
import { Route as AutomationsAutomationIdFinalActionRouteImport } from './routes/automations/$automationId/final-action'
import { Route as AutomationsAutomationIdIdentificationRouteImport } from './routes/automations/$automationId/identification'
import { Route as AutomationsAutomationIdKeywordRouteImport } from './routes/automations/$automationId/keyword'
import { Route as AutomationsAutomationIdPublicReplyRouteImport } from './routes/automations/$automationId/public-reply'
import { Route as AutomationsAutomationIdReviewRouteImport } from './routes/automations/$automationId/review'
import { Route as AutomationsAutomationIdTestRouteImport } from './routes/automations/$automationId/test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AutomationsIndexRoute = AutomationsIndexRouteImport.update({
  id: '/automations/',
  path: '/automations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsAutomationIdRouteRoute =
  AutomationsAutomationIdRouteRouteImport.update({
    id: '/automations/$automationId',
    path: '/automations/$automationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AutomationsAutomationIdIndexRoute =
  AutomationsAutomationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdActivityRoute =
  AutomationsAutomationIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdContentRoute =
  AutomationsAutomationIdContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdDirectMessageRoute =
  AutomationsAutomationIdDirectMessageRouteImport.update({
    id: '/direct-message',
    path: '/direct-message',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdFinalActionRoute =
  AutomationsAutomationIdFinalActionRouteImport.update({
    id: '/final-action',
    path: '/final-action',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdIdentificationRoute =
  AutomationsAutomationIdIdentificationRouteImport.update({
    id: '/identification',
    path: '/identification',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdKeywordRoute =
  AutomationsAutomationIdKeywordRouteImport.update({
    id: '/keyword',
    path: '/keyword',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdPublicReplyRoute =
  AutomationsAutomationIdPublicReplyRouteImport.update({
    id: '/public-reply',
    path: '/public-reply',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdReviewRoute =
  AutomationsAutomationIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)
const AutomationsAutomationIdTestRoute =
  AutomationsAutomationIdTestRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AutomationsAutomationIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/automations/': typeof AutomationsIndexRoute
  '/automations/$automationId/activity': typeof AutomationsAutomationIdActivityRoute
  '/automations/$automationId/content': typeof AutomationsAutomationIdContentRoute
  '/automations/$automationId/direct-message': typeof AutomationsAutomationIdDirectMessageRoute
  '/automations/$automationId/final-action': typeof AutomationsAutomationIdFinalActionRoute
  '/automations/$automationId/identification': typeof AutomationsAutomationIdIdentificationRoute
  '/automations/$automationId/keyword': typeof AutomationsAutomationIdKeywordRoute
  '/automations/$automationId/public-reply': typeof AutomationsAutomationIdPublicReplyRoute
  '/automations/$automationId/review': typeof AutomationsAutomationIdReviewRoute
  '/automations/$automationId/test': typeof AutomationsAutomationIdTestRoute
  '/automations/$automationId/': typeof AutomationsAutomationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/automations': typeof AutomationsIndexRoute
  '/automations/$automationId/activity': typeof AutomationsAutomationIdActivityRoute
  '/automations/$automationId/content': typeof AutomationsAutomationIdContentRoute
  '/automations/$automationId/direct-message': typeof AutomationsAutomationIdDirectMessageRoute
  '/automations/$automationId/final-action': typeof AutomationsAutomationIdFinalActionRoute
  '/automations/$automationId/identification': typeof AutomationsAutomationIdIdentificationRoute
  '/automations/$automationId/keyword': typeof AutomationsAutomationIdKeywordRoute
  '/automations/$automationId/public-reply': typeof AutomationsAutomationIdPublicReplyRoute
  '/automations/$automationId/review': typeof AutomationsAutomationIdReviewRoute
  '/automations/$automationId/test': typeof AutomationsAutomationIdTestRoute
  '/automations/$automationId': typeof AutomationsAutomationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/users': typeof UsersRoute
  '/workspace': typeof WorkspaceRoute
  '/automations/$automationId': typeof AutomationsAutomationIdRouteRouteWithChildren
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/automations/': typeof AutomationsIndexRoute
  '/automations/$automationId/activity': typeof AutomationsAutomationIdActivityRoute
  '/automations/$automationId/content': typeof AutomationsAutomationIdContentRoute
  '/automations/$automationId/direct-message': typeof AutomationsAutomationIdDirectMessageRoute
  '/automations/$automationId/final-action': typeof AutomationsAutomationIdFinalActionRoute
  '/automations/$automationId/identification': typeof AutomationsAutomationIdIdentificationRoute
  '/automations/$automationId/keyword': typeof AutomationsAutomationIdKeywordRoute
  '/automations/$automationId/public-reply': typeof AutomationsAutomationIdPublicReplyRoute
  '/automations/$automationId/review': typeof AutomationsAutomationIdReviewRoute
  '/automations/$automationId/test': typeof AutomationsAutomationIdTestRoute
  '/automations/$automationId/': typeof AutomationsAutomationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accept-invitation'
    | '/users'
    | '/workspace'
    | '/automations/$automationId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/automations/'
    | '/automations/$automationId/activity'
    | '/automations/$automationId/content'
    | '/automations/$automationId/direct-message'
    | '/automations/$automationId/final-action'
    | '/automations/$automationId/identification'
    | '/automations/$automationId/keyword'
    | '/automations/$automationId/public-reply'
    | '/automations/$automationId/review'
    | '/automations/$automationId/test'
    | '/automations/$automationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accept-invitation'
    | '/users'
    | '/workspace'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/automations'
    | '/automations/$automationId/activity'
    | '/automations/$automationId/content'
    | '/automations/$automationId/direct-message'
    | '/automations/$automationId/final-action'
    | '/automations/$automationId/identification'
    | '/automations/$automationId/keyword'
    | '/automations/$automationId/public-reply'
    | '/automations/$automationId/review'
    | '/automations/$automationId/test'
    | '/automations/$automationId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/accept-invitation'
    | '/users'
    | '/workspace'
    | '/automations/$automationId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/automations/'
    | '/automations/$automationId/activity'
    | '/automations/$automationId/content'
    | '/automations/$automationId/direct-message'
    | '/automations/$automationId/final-action'
    | '/automations/$automationId/identification'
    | '/automations/$automationId/keyword'
    | '/automations/$automationId/public-reply'
    | '/automations/$automationId/review'
    | '/automations/$automationId/test'
    | '/automations/$automationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  UsersRoute: typeof UsersRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AutomationsAutomationIdRouteRoute: typeof AutomationsAutomationIdRouteRouteWithChildren
  AutomationsIndexRoute: typeof AutomationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/automations/': {
      id: '/automations/'
      path: '/automations'
      fullPath: '/automations/'
      preLoaderRoute: typeof AutomationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/$automationId': {
      id: '/automations/$automationId'
      path: '/automations/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AutomationsAutomationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/$automationId/': {
      id: '/automations/$automationId/'
      path: '/'
      fullPath: '/automations/$automationId/'
      preLoaderRoute: typeof AutomationsAutomationIdIndexRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/activity': {
      id: '/automations/$automationId/activity'
      path: '/activity'
      fullPath: '/automations/$automationId/activity'
      preLoaderRoute: typeof AutomationsAutomationIdActivityRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/content': {
      id: '/automations/$automationId/content'
      path: '/content'
      fullPath: '/automations/$automationId/content'
      preLoaderRoute: typeof AutomationsAutomationIdContentRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/direct-message': {
      id: '/automations/$automationId/direct-message'
      path: '/direct-message'
      fullPath: '/automations/$automationId/direct-message'
      preLoaderRoute: typeof AutomationsAutomationIdDirectMessageRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/final-action': {
      id: '/automations/$automationId/final-action'
      path: '/final-action'
      fullPath: '/automations/$automationId/final-action'
      preLoaderRoute: typeof AutomationsAutomationIdFinalActionRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/identification': {
      id: '/automations/$automationId/identification'
      path: '/identification'
      fullPath: '/automations/$automationId/identification'
      preLoaderRoute: typeof AutomationsAutomationIdIdentificationRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/keyword': {
      id: '/automations/$automationId/keyword'
      path: '/keyword'
      fullPath: '/automations/$automationId/keyword'
      preLoaderRoute: typeof AutomationsAutomationIdKeywordRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/public-reply': {
      id: '/automations/$automationId/public-reply'
      path: '/public-reply'
      fullPath: '/automations/$automationId/public-reply'
      preLoaderRoute: typeof AutomationsAutomationIdPublicReplyRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/review': {
      id: '/automations/$automationId/review'
      path: '/review'
      fullPath: '/automations/$automationId/review'
      preLoaderRoute: typeof AutomationsAutomationIdReviewRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
    '/automations/$automationId/test': {
      id: '/automations/$automationId/test'
      path: '/test'
      fullPath: '/automations/$automationId/test'
      preLoaderRoute: typeof AutomationsAutomationIdTestRouteImport
      parentRoute: typeof AutomationsAutomationIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AutomationsAutomationIdRouteRouteChildren {
  AutomationsAutomationIdActivityRoute: typeof AutomationsAutomationIdActivityRoute
  AutomationsAutomationIdContentRoute: typeof AutomationsAutomationIdContentRoute
  AutomationsAutomationIdDirectMessageRoute: typeof AutomationsAutomationIdDirectMessageRoute
  AutomationsAutomationIdFinalActionRoute: typeof AutomationsAutomationIdFinalActionRoute
  AutomationsAutomationIdIdentificationRoute: typeof AutomationsAutomationIdIdentificationRoute
  AutomationsAutomationIdKeywordRoute: typeof AutomationsAutomationIdKeywordRoute
  AutomationsAutomationIdPublicReplyRoute: typeof AutomationsAutomationIdPublicReplyRoute
  AutomationsAutomationIdReviewRoute: typeof AutomationsAutomationIdReviewRoute
  AutomationsAutomationIdTestRoute: typeof AutomationsAutomationIdTestRoute
  AutomationsAutomationIdIndexRoute: typeof AutomationsAutomationIdIndexRoute
}

const AutomationsAutomationIdRouteRouteChildren: AutomationsAutomationIdRouteRouteChildren =
  {
    AutomationsAutomationIdActivityRoute: AutomationsAutomationIdActivityRoute,
    AutomationsAutomationIdContentRoute: AutomationsAutomationIdContentRoute,
    AutomationsAutomationIdDirectMessageRoute:
      AutomationsAutomationIdDirectMessageRoute,
    AutomationsAutomationIdFinalActionRoute:
      AutomationsAutomationIdFinalActionRoute,
    AutomationsAutomationIdIdentificationRoute:
      AutomationsAutomationIdIdentificationRoute,
    AutomationsAutomationIdKeywordRoute: AutomationsAutomationIdKeywordRoute,
    AutomationsAutomationIdPublicReplyRoute:
      AutomationsAutomationIdPublicReplyRoute,
    AutomationsAutomationIdReviewRoute: AutomationsAutomationIdReviewRoute,
    AutomationsAutomationIdTestRoute: AutomationsAutomationIdTestRoute,
    AutomationsAutomationIdIndexRoute: AutomationsAutomationIdIndexRoute,
  }

const AutomationsAutomationIdRouteRouteWithChildren =
  AutomationsAutomationIdRouteRoute._addFileChildren(
    AutomationsAutomationIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  UsersRoute: UsersRoute,
  WorkspaceRoute: WorkspaceRoute,
  AutomationsAutomationIdRouteRoute:
    AutomationsAutomationIdRouteRouteWithChildren,
  AutomationsIndexRoute: AutomationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
