CREATE TYPE "AutomationStatus" AS ENUM ('DRAFT', 'ACTIVE', 'PAUSED', 'ARCHIVED');
CREATE TYPE "AutomationRevisionStatus" AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE "AutomationTriggerType" AS ENUM ('COMMENT_KEYWORD');
CREATE TYPE "AutomationActionType" AS ENUM ('PUBLIC_REPLY', 'PRIVATE_REPLY', 'LINK', 'CAPTURE_EMAIL', 'APPLY_TAG');
CREATE TYPE "ContentProvider" AS ENUM ('INSTAGRAM', 'TIKTOK');
CREATE TYPE "ContentMode" AS ENUM ('SIMULATED', 'REAL');
CREATE TYPE "ContentType" AS ENUM ('POST', 'VIDEO');
CREATE TABLE "Content" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "provider" "ContentProvider" NOT NULL DEFAULT 'INSTAGRAM', "mode" "ContentMode" NOT NULL DEFAULT 'SIMULATED', "contentType" "ContentType" NOT NULL DEFAULT 'POST', "title" TEXT NOT NULL, "externalContentId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Content_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Automation" ("id" TEXT NOT NULL, "organizationId" TEXT NOT NULL, "createdByUserId" TEXT NOT NULL, "status" "AutomationStatus" NOT NULL DEFAULT 'DRAFT', "currentPublishedRevisionId" TEXT, "activeContentId" TEXT, "activeKeywordNormalized" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "publishedAt" TIMESTAMP(3), "pausedAt" TIMESTAMP(3), CONSTRAINT "Automation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AutomationRevision" ("id" TEXT NOT NULL, "automationId" TEXT NOT NULL, "version" INTEGER NOT NULL, "status" "AutomationRevisionStatus" NOT NULL DEFAULT 'DRAFT', "name" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "publishedAt" TIMESTAMP(3), CONSTRAINT "AutomationRevision_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AutomationTarget" ("id" TEXT NOT NULL, "revisionId" TEXT NOT NULL, "contentId" TEXT NOT NULL, CONSTRAINT "AutomationTarget_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AutomationTrigger" ("id" TEXT NOT NULL, "revisionId" TEXT NOT NULL, "type" "AutomationTriggerType" NOT NULL DEFAULT 'COMMENT_KEYWORD', "keyword" TEXT NOT NULL, "keywordNormalized" TEXT NOT NULL, CONSTRAINT "AutomationTrigger_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AutomationAction" ("id" TEXT NOT NULL, "revisionId" TEXT NOT NULL, "position" INTEGER NOT NULL, "type" "AutomationActionType" NOT NULL, "config" JSONB NOT NULL, CONSTRAINT "AutomationAction_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Automation_currentPublishedRevisionId_key" ON "Automation"("currentPublishedRevisionId");
CREATE UNIQUE INDEX "Content_organizationId_provider_mode_contentType_externalContentId_key" ON "Content"("organizationId", "provider", "mode", "contentType", "externalContentId");
CREATE UNIQUE INDEX "AutomationRevision_automationId_version_key" ON "AutomationRevision"("automationId", "version");
CREATE UNIQUE INDEX "AutomationTarget_revisionId_key" ON "AutomationTarget"("revisionId");
CREATE UNIQUE INDEX "AutomationTrigger_revisionId_key" ON "AutomationTrigger"("revisionId");
CREATE UNIQUE INDEX "AutomationAction_revisionId_position_key" ON "AutomationAction"("revisionId", "position");
CREATE INDEX "Automation_organizationId_status_updatedAt_idx" ON "Automation"("organizationId", "status", "updatedAt");
CREATE INDEX "Content_organizationId_updatedAt_idx" ON "Content"("organizationId", "updatedAt");
CREATE UNIQUE INDEX "Automation_one_draft_revision" ON "AutomationRevision"("automationId") WHERE "status" = 'DRAFT';
CREATE UNIQUE INDEX "Automation_active_trigger" ON "Automation"("organizationId", "activeContentId", "activeKeywordNormalized") WHERE "status" = 'ACTIVE';
ALTER TABLE "Content" ADD CONSTRAINT "Content_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Automation" ADD CONSTRAINT "Automation_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization"("id") ON DELETE CASCADE;
ALTER TABLE "Automation" ADD CONSTRAINT "Automation_createdByUserId_fkey" FOREIGN KEY ("createdByUserId") REFERENCES "User"("id");
ALTER TABLE "Automation" ADD CONSTRAINT "Automation_currentPublishedRevisionId_fkey" FOREIGN KEY ("currentPublishedRevisionId") REFERENCES "AutomationRevision"("id");
ALTER TABLE "AutomationRevision" ADD CONSTRAINT "AutomationRevision_automationId_fkey" FOREIGN KEY ("automationId") REFERENCES "Automation"("id") ON DELETE CASCADE;
ALTER TABLE "AutomationTarget" ADD CONSTRAINT "AutomationTarget_revisionId_fkey" FOREIGN KEY ("revisionId") REFERENCES "AutomationRevision"("id") ON DELETE CASCADE;
ALTER TABLE "AutomationTarget" ADD CONSTRAINT "AutomationTarget_contentId_fkey" FOREIGN KEY ("contentId") REFERENCES "Content"("id");
ALTER TABLE "AutomationTrigger" ADD CONSTRAINT "AutomationTrigger_revisionId_fkey" FOREIGN KEY ("revisionId") REFERENCES "AutomationRevision"("id") ON DELETE CASCADE;
ALTER TABLE "AutomationAction" ADD CONSTRAINT "AutomationAction_revisionId_fkey" FOREIGN KEY ("revisionId") REFERENCES "AutomationRevision"("id") ON DELETE CASCADE;
